### ISSUE TITLE
Better error handling when system runs out of memory

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#192]
Trying to run `ghost install --no-setup` I got this error:

>$ ghost install --no-setup
>$ cat ghost-cli-debug-xxx.log 

```
Debug Information:
    Node Version: v6.10.3
    Ghost-CLI Version: 1.0.0-alpha.16
    Environment: production
    Command: 'ghost install --no-setup'
An error occurred.
Message: 'Command failed: yarn install --no-emoji --no-progress
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
'

Stack: Error: Command failed: yarn install --no-emoji --no-progress
yarn install v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...

    at Promise.all.then.arr (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:210:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Not sure what caused this? 

Trying to run the installer again results in:

>$  ghost install --no-setup

```
A SystemError occured.

Message: Current directory is not empty, Ghost cannot be installed here.

Debug Information:
    Node Version: v6.10.3
    Ghost-CLI Version: 1.0.0-alpha.16
    Environment: production
    Command: 'ghost install --no-setup'
```

I understand why this is, but it's not very helpful 😁   - if the installer fails, I should be able to try again I think?

First issue is something I want to get to the bottom of, clean re-installs is something for later.

**Comment by acburdine** [comment]
@ErisDS It looks like something got screwed up with yarn. Have you been able to reproduce this multiple times?

**Comment by acburdine** [comment]
> No amount of rerunning it sorted the problem.

Just to make sure I understand what you're saying - you tried running it in a different folder and it gave the same error?

**Comment by ErisDS** [comment]
I cleared out the folder, but yes got the same error. I've since destroyed the droplet I think, sorry.

**Comment by acburdine** [comment]
Hmm...well based on the error shown I'm 99% sure this is something do with yarn. I'll try testing on a droplet at somepoint today, but if I can't reproduce it there my feeling is to wait and see if it happens again or if anyone else reports it?

**Comment by ErisDS** [comment]
Yeah I'll try and reproduce again as well. I realise it's a bit of a crappy report!

**Comment by acburdine** [comment]
@ErisDS @chanssl (from the closed duplicate issue): would you both mind trying to reproduce this issue with ghost-cli alpha.18?

I don't know if I've necessarily fixed the issue, but I fixed the error handling so if this particular error _does_ happen again, it will be reported better by the CLI.

Thanks!

**Comment by chanssl** [comment]
Looks like my system was running out of memory. I will try again after I upgrade the vps .

> npm i -g ghost-cli


	npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
	Killed        .....] \ extract:ghost-cli: sill doParallel extract 477


> npm install -g ghost-cli


	npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
	Killed        .....] - extract:configstore: sill gunzTarPerm extractEntry test/fixtures/cosmic.js


> npm install -g ghost-cli


	npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
	Killed         ....] | extract:extsprintf: verb gentlyRm don't care about contents; nuking /usr/lib/node_modules/.staging/listr-a04f9b00/node_


> yarn global add ghost-cli


	yarn global v0.24.6
	[1/4] Resolving packages...
	warning ghost-cli > ghost-ignition > bunyan-loggly > loggly > request > node-uuid@1.4.8: Use uuid module instead
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	[-/3] ⠈ waiting...
	[2/3] ⠈ ursa: CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
	[-/3] ⠁ waiting...Killed

**Comment by tmack8001** [comment]
I'm getting this exact same experience even on 1.0.0.alpha-19. My installation of ghost 1.0 in on a raspberrypi 3, which has been running my ghost pre-1.0 installation for a while with no problems.

Here is the related logs I see with the issue highlighting the problems faced (was also a similar or exact same problem on 1.0.0.alpha-18). Below is logs from --verbose as the logs from non verbose weren't very useful.

```
[04:05:54] Downloading and installing Ghost v1.0.0-beta.1 [failed]
[04:05:54] → Command failed: yarn install --no-emoji --no-progress
error Error parsing JSON at "/home/pi/.cache/yarn/v1/npm-ajv-4.11.7-8655a5d86d0824985cc471a1d913fb6729a0ec48/package.json", "/home/pi/.cache/yarn/v1/npm-ajv-4.11.7-8655a5d86d0824985cc471a1d913fb6729a0ec48/package.json: Unexpected token � in JSON at position 0".

yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

A ProcessError occured.

Error occurred running command: 'yarn install --no-emoji --no-progress'

Exit code: 1
```

Also the versions of various software being used is below: 

```
Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0-alpha.19
    Environment: production
    Command: 'ghost install --no-stack --verbose'
$ yarn --version
0.24.6
```

**Comment by acburdine** [comment]
@evilpilaf your error is actually a different one - it's the same as being reported in #228

**Comment by acburdine** [comment]
My _thought_ is that this problem was originally related to an out-of-memory issue. The error handling around this has been fixed, so I'm going to go ahead and close this. If this does turn out to be something other than an out-of-memory issue then we can either reopen this issue or create a new one 😄

**Comment by tmack8001** [comment]
Austin I was still getting this and the error handling didn't lead me to
believe anything was OOM, how did error handling change? I'm confused...

**Comment by acburdine** [comment]
@tmack8001 can you post your `ghost-cli-debug-<timestamp>.log` file? That will contain some more contextual info as to why Yarn is exiting.

**Comment by kirrg001** [comment]
Happened for me on `ghost install local`.

```
A ProcessError occured.

Error occurred running command: 'yarn install --no-emoji --no-progress'

Exit code: 1


Debug Information:
    Node Version: v6.10.3
    Ghost-CLI Version: 1.0.0-beta.3
    Environment: development
    Command: 'ghost install local'

Additional log info available in: /root/.ghost/logs/ghost-cli-debug-2017-07-05T10_08_17_269Z.log
root@dev-kate-01:~/tests/2# cat  /root/.ghost/logs/ghost-cli-debug-2017-07-05T10_08_17_269Z.log
Debug Information:
    Node Version: v6.10.3
    Ghost-CLI Version: 1.0.0-beta.3
    Environment: development
    Command: 'ghost install local'
Error occurred running command: 'yarn install --no-emoji --no-progress'

Exit code: 1

--------------- stdout ---------------
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
info If you think this is a bug, please open a bug report with the information provided in "/root/tests/2/versions/1.0.0-beta.2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


--------------- stderr ---------------
warning Error running install script for optional dependency: "/root/tests/2/versions/1.0.0-beta.2/node_modules/dtrace-provider: spawn ENOMEM"
error An unexpected error occurred: "/root/tests/2/versions/1.0.0-beta.2/node_modules/jsonpath: spawn ENOMEM".
```

**Comment by acburdine** [comment]
@kirrg001 that looks like an out of memory exception.

**Comment by kirrg001** [comment]
@acburdine Yes. Can we improve the output?

**Comment by tmack8001** [comment]
I'm on holiday without access to my raspberry pi which I was having issues
on. I'll check in after my holiday is finished.


On Jul 5, 2017 11:13 AM, "Katharina Irrgang" <notifications@github.com>
wrote:

@acburdine <https://github.com/acburdine> Yes. Can we improve the output?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TryGhost/Ghost-CLI/issues/192#issuecomment-313061887>,
or mute the thread

**Comment by arvindvenkataramani** [comment]
Definitely an out of memory exception (Ubuntu 16.04.2 with node 6.11.1); I have 512M on a droplet – adding a 1G swap file fixed it.

**Comment by millerone** [comment]
I'm getting the same error message but i'm on Win 10 (surface laptop) using ghost-cli version 1.0.3
Is there an easy way to fix it?
Thanks!

**Comment by tmack8001** [comment]
Here is the contents of my error log.

```
$ more /home/pi/.ghost/logs/ghost-cli-debug-2017-08-02T03_52_44_600Z.log
Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.3
    Environment: production
    Command: 'ghost install'
Error occurred running command: 'yarn install --no-emoji --no-progress'

Exit code: 1

--------------- stdout ---------------
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information p
rovided in "/var/www/ghost/trevor-mack.com/versions/1.3.0/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.


--------------- stderr ---------------
error An unexpected error occurred: "/home/pi/.cache/yarn/v1/npm-ajv-4.11.7-8655
a5d86d0824985cc471a1d913fb6729a0ec48/package.json: Unexpected token � in JSON at
 position 0".
```

**Comment by tmack8001** [comment]
understanding that I'm on a unsupported platform, but I like others have been using my raspberry pi for hosting ghost at home for years so would like to see / help get this working with 1.0.x releases again

attempting to install ghost via yarn directly bypassing the ghost-cli gives me the same/similar error

**Comment by acburdine** [comment]
@tmack8001 your error looks different than the original error for this issue. It looks like something in your Yarn cache might be corrupted. My suggestion is to try clearing your yarn cache (`ghost buster` is a convenient alias for this 😛 ) and installing again to see if that fixes it.

**Comment by tmack8001** [comment]
After going through my running process list and issuing a ```kill -9 <>``` on non pertinent stuff that was taking up system memory (my webserver, mysql, python, java, etc) I was able to successfully get a ghost installation and setup completed.

From talking with @acburdine today we believe the above error log I posted was from a follow on installation after a OOM issue with yarn which then had a corrupted / invalid cached file under the ~/.cache/yarn directory. I had seen this on multiple different npm modules, but the error messages looked like the above. If I ever run into failures in the future I'll try and post here or in another issue depending on cause.

**Comment by millerone** [comment]
I can confirm that  the command 'yarn cache clean' solved the problem.
Now it works like a charm.
Thanks

**Comment by Nopzen** [comment]
can confirm OP was mem issue for me, I was running a Droplet 512mb ram,  resized it and it seemed to make it work.

**Comment by kevmille** [comment]
> yarn cache clean

@francescomugnai:
You are a godsend. I was trying to install Ghost 4.3.2 on my Ubuntu 20.04 instance at DigitalOcean. I kept getting the same A ProcessError occurred messages. Spent nearly a day searching DuckDuckGo and Google for the answer. $yarn cache clean did it for me and I was able to install Ghost, finally.

Thanks for this. I think many guys/gals will thank you for this. This should be be included in the Troubleshoot area of Ghost.
